[package]
name = "donutdb_project"
version = "0.1.0"
edition = "2021"

[dependencies]
warp = "0.3"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
ring = "0.17"
tokio = { version = "1.0", features = ["full"] }
chrono = "0.4"
